### ISSUE TITLE
Error when sampling data 

### ISSUE THREAD

**Issue by nlagrang** [aimclub/BAMT#64]
Hello,

I try to replicate the following code [(https://bamt.readthedocs.io/en/latest/examples/learn_sampling_predict.html)](url) but when i learn the parameters i get the following error : AttributeError: 'NoneType' object has no attribute 'split'. I give you the details of the errors : [error.pdf](https://github.com/aimclub/BAMT/files/11906954/error.pdf)
And I have the impression that learning the structure isn't complete: the progress bar is at 0%. 
When I set the use_mixture parameter to False, I can generate data, but the number of samples generated does not correspond to the number given at the start (there are fewer).

Thanks,

Nikita

**Comment by Anaxagor** [comment]
Yes, the error appears at the parametric training stage, since apparently the version of scikit-learn is not quite suitable, try the version, for example, 1.2.0

**Comment by nlagrang** [comment]
Thanks for the quick reply, but I still have the same error with the scikit-learn 1.2.0

**Comment by Anaxagor** [comment]
Ok, then you can try two more things:
1) Install the package threadpoolctl==3.1.0
2) Check if all discrete variables are exactly of type int or string.

**Comment by nlagrang** [comment]
Thanks it worked after installing the version threadpoolctl==3.1.0. 
I have one last problem when I use the command sampled_data = bn.sample(1000) , I don't get 1000 samples but 943 and it varies between executions

**Comment by nlagrang** [comment]
Ok, thank you for this information and your help ! Now everything works
