### ISSUE TITLE
Roman

### ISSUE THREAD

**Issue by fingoldo** [aimclub/BAMT#71]
Привет, предлагаю исправить в файле selbst.ini

C:\Users\Roman\BAMT\Nodes_data 

на 

%%LOCALAPPDATA%%\aimclub\BAMT\Nodes_data

И оставить

log_conf_loc = logging.conf

В файле bamt\networks\base.py придётся добавить expandvars:

```
STORAGE = os.path.expandvars(config.get(
    "NODES", "models_storage", fallback="models_storage is not defined"
))
```

Или вообще использовать [platformdirs](https://github.com/platformdirs/platformdirs) и захардкодить `user_data_dir(appname, appauthor`).

Также мне потребовалось обновить 

pip install threadpoolctl -U

иначе не читался конфиг blas и fit_parameters падал. Предлагаю threadpoolctl добавить в зависимости, или хотя бы прописать этот кейс в readme.

**Comment by jrzkaminski** [comment]
Здравствуйте!
Спасибо за Ваш issue.
Подскажите, пожалуйста, какую версию `python` вы использовали и какая версия `threadpoolctl` стояла до и после.

**Comment by fingoldo** [comment]
> Здравствуйте! Спасибо за Ваш issue. Подскажите, пожалуйста, какую версию `python` вы использовали и какая версия `threadpoolctl` стояла до и после.
> 
> По поводу `selbst.ini` - пути там не захардкожены и он создается автоматически для каждого юзера. Что конкретно у Вас пошло не так?

Python 3.9.13

Successfully uninstalled threadpoolctl-2.2.0
Successfully installed threadpoolctl-3.2.0

Не знаю, у меня почему-то бибилиотека решила, что юзер Roman )

**Comment by jrzkaminski** [comment]
Хм, это странновато, вы можете удалить `selbst.ini` и он сгенерируется снова.
По поводу `threadpoolctl`: если ставить все в чистую среду, то ставится `threadpoolctl == 3.1.0`. Мы обсудим добавление этой либы в requirements, хотя мы напрямую ее не используем.

**Comment by Roman223** [comment]
Hello @fingoldo,

This bug caused by me, on PyPi there was a package with .ini from me. It has fixed in 1.1.45.

Now you can just update BAMT, or you can remove wrong `selbst.ini` on your current version and BAMT will create a new one.
